In [11]:
import numpy as np 
import itertools
from sklearn.datasets import load_breast_cancer

# Zadanie 1
Wygeneruj losową tablice 100 x 10, która będzie reprezentować 100 punktów w 10 wymiarowej przestrzeni. Napisz funkcję, która policzy odległość euklidesową pomiędzy każdą parą punktów, czy potrafisz zrobić to w jednej linijce, bez użycia żadnych pętli/wytworników pętli? Przypomnienie, dla dwóch wektorów  xx  i  yy  odległość euklidesową liczymy ze wzoru: 

$$
d(x,y)=\|x-y\|_2^2=\sum_{i=1}^n |x_i-y_i|^2.
$$

In [3]:
A = np.random.randint(10, size=(100, 10))
list(map(lambda x: np.linalg.norm(x), list(itertools.combinations(A, 2))))

[24.55605831561735,
 23.811761799581316,
 24.331050121192877,
 27.184554438136374,
 27.0,
 23.979157616563597,
 23.0,
 26.77685567799177,
 25.25866188063018,
 26.362852652928137,
 24.79919353527449,
 25.13961017995307,
 22.715633383201094,
 23.108440016582687,
 22.80350850198276,
 26.210684844162312,
 25.573423705088842,
 24.819347291981714,
 25.059928172283335,
 23.790754506740637,
 23.769728648009426,
 24.454038521274967,
 23.68543856465402,
 24.331050121192877,
 25.099800796022265,
 22.538855339169288,
 25.357444666211933,
 23.40939982143925,
 25.179356624028344,
 25.03996805109783,
 23.916521486202797,
 23.388031127053,
 22.38302928559939,
 24.95996794869737,
 22.06807649071391,
 26.267851073127396,
 23.57965224510319,
 26.645825188948457,
 21.118712081942874,
 22.58317958127243,
 23.916521486202797,
 24.24871130596428,
 25.436194683953808,
 22.956480566497994,
 23.259406699226016,
 25.632011235952593,
 23.065125189341593,
 23.895606290697042,
 21.863211109075447,
 26.5141471671257

# Zadanie 2

Wygeneruj losową tablicę z wielowymiarowego rozkładu normalnego (procedura random.multivariate_normal), która będzie reprezentować 100 punktów w 5 wymiarowej przestrzeni. Napisz funkcję do normalizacji zbioru punktów (zrób to w jednej linijce, bez użycia pętli):

$$
x_{ij} = \frac{x_{ij}-\mu_j}{\sigma_j},
$$

gdzie  $μ_j$  to średnia, a  $σ_j$  to odchylenie standardowe po  $j$-tej kolumnie, zaś  $x_{ij}$  to  $j$-ta współrzędna  $i$ -tego wektora.

Policz średnią i macierz kowariancji tak przekształconych danych. Co zaobserwowałeś?

In [6]:
mean = np.array([0, 0, 0, 0, 0])
cov = np.array([[1, 0.1, 0.1, 0.1, 0.1], [0.1, 1, 0.1, 0.1, 0.1], [0.1, 0.1, 1, 0.1, 0.1], [0.1, 0.1, 0.1, 1, 0.1], [0.1, 0.1, 0.1, 0.1, 1]])
A = np.random.multivariate_normal(mean, cov, 100)
A = ((A - mean).reshape(20, 5, 5) / cov).reshape(100, 5)

In [7]:
mean = np.mean(A, 0)
np.dot(A-mean, (A-mean).T) / (100-1)

array([[ 2.23675259, -0.45773763, -1.97079925, ...,  0.39688356,
        -2.07039811,  1.79260599],
       [-0.45773763,  1.20333038,  0.85456839, ..., -0.12856786,
         0.31996066,  0.52576509],
       [-1.97079925,  0.85456839,  4.7362526 , ..., -2.78271078,
         0.40251096,  0.32017846],
       ...,
       [ 0.39688356, -0.12856786, -2.78271078, ...,  3.58893406,
         0.29869874, -0.88090458],
       [-2.07039811,  0.31996066,  0.40251096, ...,  0.29869874,
         3.42851175, -2.57775291],
       [ 1.79260599,  0.52576509,  0.32017846, ..., -0.88090458,
        -2.57775291,  3.01102347]])

In [8]:
np.cov(A)

array([[ 56.19736316,  -3.29328227, -56.56524005, ...,  26.61661705,
        -26.76511285,  38.38923681],
       [ -3.29328227,  27.16770126,  22.64762681, ..., -10.72522552,
         -4.82864076,  23.55009522],
       [-56.56524005,  22.64762681, 100.56456023, ..., -57.01663958,
         31.00809141,  -7.7685046 ],
       ...,
       [ 26.61661705, -10.72522552, -57.01663958, ...,  65.85949485,
        -30.66104264,   4.63761264],
       [-26.76511285,  -4.82864076,  31.00809141, ..., -30.66104264,
         22.40846659, -22.94814632],
       [ 38.38923681,  23.55009522,  -7.7685046 , ...,   4.63761264,
        -22.94814632,  56.8658454 ]])

### Różnica wynika z faktu, że np.cov oblicza kowariancję między wektorami wierszowymi,a np.mean oblicza średnią wektorów kolumn i kiedy mamy działanie (test - mean) obliczenia są również transmitowane wzdłuż kolumny.

In [9]:
mean = np.mean(A.T, 0)
np.dot(A-mean[:, None], (A-mean[:, None]).T) / (5-1)

array([[ 56.19736316,  -3.29328227, -56.56524005, ...,  26.61661705,
        -26.76511285,  38.38923681],
       [ -3.29328227,  27.16770126,  22.64762681, ..., -10.72522552,
         -4.82864076,  23.55009522],
       [-56.56524005,  22.64762681, 100.56456023, ..., -57.01663958,
         31.00809141,  -7.7685046 ],
       ...,
       [ 26.61661705, -10.72522552, -57.01663958, ...,  65.85949485,
        -30.66104264,   4.63761264],
       [-26.76511285,  -4.82864076,  31.00809141, ..., -30.66104264,
         22.40846659, -22.94814632],
       [ 38.38923681,  23.55009522,  -7.7685046 , ...,   4.63761264,
        -22.94814632,  56.8658454 ]])

# Zadanie 3

Wypełni 100-elementową tablicę liczbami losowymi naturalnymi z zakresu  $[5,15]$  i policz liczbę wystąpień tych liczb. Która z tych liczb najczęściej występuje w tak wygenerowanej tablicy?
Wskazówka: zobacz funkcje: bincount, argmax.

In [10]:
x = np.random.randint(low=5, high=16, size=(100,))
l = np.bincount(x)
display(["{:<2d} -> {}".format(el[0], el[1]) for el in enumerate(l)])
np.argmax(l)

['0  -> 0',
 '1  -> 0',
 '2  -> 0',
 '3  -> 0',
 '4  -> 0',
 '5  -> 10',
 '6  -> 7',
 '7  -> 13',
 '8  -> 13',
 '9  -> 6',
 '10 -> 10',
 '11 -> 11',
 '12 -> 8',
 '13 -> 9',
 '14 -> 6',
 '15 -> 7']

7

# Zadanie 4

Korzystając z poniższego kodu zaimportuj dane **breast cancer**, który składa się z 2 elementów: macierzy  $X$  o wymiarach 569 x 30 oraz wektora  $y$ o długości 569. Macierz  $X$  opisuje badania 683 pacjentów, a wektor  $y$  ich diagnozy.

In [13]:
X, y  = load_breast_cancer(return_X_y=True)
print(X.shape)
print(y.shape)

(569, 30)
(569,)


Za pomocą biblioteki **numpy** przenumeruj wektor  $y$ , tzn zamień wartości $0$ i $1$ na $-1$ i $+1$. Przeskaluj macierz  $X$ , tak żeby wartości w każdej kolumnie mieściły się w zakresie  $[0,1]$ , innymi słowy przeskaluj niezależnie każdą kolumnę  $X_i$  według poniższej procedury: 

$$
X_i=\frac{X_i-min(X_i)}{max(X_i)-min(X_i)}.
$$

In [15]:
y[y==0] = -1
y

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1,  1,  1,  1,
        1,  1, -1, -1,  1, -1, -1,  1,  1,  1,  1, -1,  1, -1, -1,  1,  1,
        1,  1, -1,  1, -1, -1,  1, -1,  1, -1, -1,  1,  1,  1, -1, -1,  1,
       -1, -1, -1,  1,  1,  1, -1,  1,  1, -1, -1,  1,  1,  1, -1, -1,  1,
        1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
       -1,  1, -1, -1,  1,  1,  1, -1, -1,  1, -1,  1, -1, -1,  1, -1, -1,
        1,  1, -1,  1,  1, -1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1,  1,  1,  1,  1, -1, -1,  1, -1,  1,  1, -1, -1,  1,
        1, -1, -1,  1,  1,  1,  1, -1,  1,  1, -1, -1, -1,  1, -1,  1, -1,
        1,  1,  1, -1,  1,  1, -1, -1,  1, -1, -1, -1, -1,  1, -1, -1, -1,
        1, -1,  1, -1,  1,  1, -1,  1, -1, -1, -1, -1,  1,  1, -1, -1,  1,
        1,  1, -1,  1,  1

In [16]:
for i in range(X.shape[1]):
    X[:,i] = (X[:,i] - np.min(X[:,i])) / (np.max(X[:,1]) - np.min(X[:,1]))
X

array([[3.72303010e-01, 2.26580994e-02, 7.90100000e+01, ...,
        2.65400000e-01, 3.03600000e-01, 6.38600000e-02],
       [4.59553602e-01, 2.72573554e-01, 8.91100000e+01, ...,
        1.86000000e-01, 1.18500000e-01, 3.39800000e-02],
       [4.29793710e-01, 3.90260399e-01, 8.62100000e+01, ...,
        2.43000000e-01, 2.04800000e-01, 3.25400000e-02],
       ...,
       [3.25295908e-01, 6.21237741e-01, 6.45100000e+01, ...,
        1.41800000e-01, 6.53000000e-02, 2.31600000e-02],
       [4.60568143e-01, 6.63510315e-01, 9.63100000e+01, ...,
        2.65000000e-01, 2.52200000e-01, 6.89600000e-02],
       [2.63442678e-02, 5.01521813e-01, 4.13000000e+00, ...,
        0.00000000e+00, 1.30600000e-01, 1.53500000e-02]])